name: Tests
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install ubuntu dependencies
        run: sudo apt-get install ffmpeg
        if: matrix.os == 'ubuntu-18.04'
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Typecheck
        run: yarn types
      - name: Unit Tests
        run: yarn test
      - name: Prepare for Integration Tests
        run: yarn demo:install && yarn demo:link && yarn demo:build
      - name: Integration Tests
        run: yarn test:integration
