name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Link
        run: yarn link
      - name: Lint
        run: yarn lint
      - name: Unit
        run: yarn test:unit
      - name: Install & Link Percy
        run: node install-and-link.js
        working-directory: "tests/integration"
      - name: React
        uses: percy/storybook-action@v0.1.3
        with:
          working-directory: "tests/integration/storybook-for-react"
          custom-command: "yarn storybook:percy"
        env:
          PERCY_TOKEN: ${{ secrets.REACT_PERCY_TOKEN }}
